name: Cleanup Workflow Runs

on:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  cleanup:
    name: Cleanup workflow runs
    runs-on: ubuntu-latest

    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 30
